fresh/fresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^urls/',include('fresheveryday.urls')),
    url(r'^',include('df_goods.urls')),
    url(r'^cart/', include('py_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),

]

fresh/fresheveryday/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^login/$',views.login),
    url(r'^register/$',views.register),
    
    url(r'^detail/$',views.detail),
    url(r'^place_order/$', views.place_order),
    url(r'^user_center_info/$', views.user_center_info),
    url(r'^user_center_order/$', views.user_center_order),
    url(r'^user_center_site/$', views.user_center_site),
    url(r'^pic_handle/$',views.pic_handle),
    url(r'^pic_handle1/$',views.pic_handle1),
    url(r'^pic_handle2/$', views.pic_handle2),
    url(r'^loginout/$',views.loginout),
    url(r'^register1/$',views.register1),
    url(r'^user_center_orders(\d+)/$',views.user_center_orders),

]

fresh/df_order/models.py
#coding=utf-8
from django.db import models
# Create your models here.

class OrderInfo(models.Model):
    oid=models.CharField(max_length=20,primary_key=True)#时间+用户编号
    user=models.ForeignKey('fresheveryday.FreshInfo')
    odate=models.DateTimeField(auto_now_add=True)
    oIsPay=models.BooleanField(default=False)
    ototal=models.DecimalField(max_digits=6,decimal_places=2)
    oaddress=models.CharField(max_length=150)

class OrderDetailInfo(models.Model):
    goods=models.ForeignKey('df_goods.GoodsInfo')
    order=models.ForeignKey(OrderInfo)
    price=models.DecimalField(max_digits=5,decimal_places=2)
    count=models.IntegerField()

fresh/fresheveryday/models.py
from django.db import models

# Create your models here.

class FreshInfo(models.Model):
    fname = models.CharField(max_length=20)
    fpwd = models.CharField(max_length=40)
    femail = models.CharField(max_length=30)
    frecipients = models.CharField(max_length=20,default='')
    faddress = models.CharField(max_length=100,default='')
    fyoubian = models.CharField(max_length=10,default='')
    fphone = models.CharField(max_length=20,default='')

fresh/fresheveryday/views.py
# coding=utf-8
from django.shortcuts import render,redirect
from models import FreshInfo
from django.template import RequestContext
from django.http import HttpResponse,JsonResponse
from django.http import HttpResponseRedirect
from . import decorator
from hashlib import sha1
from py_cart.models import *
from df_order.models import *
from django.core.paginator import Paginator,Page
# Create your views here.
def register(request):
    return render(request,'fresheveryday/register.html')
def login(request):
    return render(request,'fresheveryday/login.html')

def place_order(request):
    return render(request,'fresheveryday/place_order.html')

def detail(request):
    response = render(request, 'fresheveryday/detail.html')
    re = request.GET
    gid = re.get('a')
    liulan = request.COOKIES.get('list','')
    if liulan == '':
        response.set_cookie('list',gid)
    else:
        liulan_list = liulan.split(',')
        if liulan in liulan_list:
            liulan_list.remove(gid)
            liulan_list.insert(0,gid)
        if len(liulan_list)>5:
            liulan_list.pop()
        liulan2 = ','.join(liulan_list)
        response.set_cookie('list', liulan2)
    return response

@decorator.login
def user_center_info(request):
    cart = CartInfo.objects.all()
    name = request.session['user_name']
    data = FreshInfo.objects.get(fname=name)
    phone = data.fphone
    add = data.faddress
    goods_list = []
    liulan = request.COOKIES.get('list','')
    if liulan != '':
        liulan_list = liulan.split(',')
        for i in liulan_list:
            goods_list.append(GoodsInfo.objects.get(id = int(i)))
    return render(request,'fresheveryday/user_center_info.html',{'name':name,'phone':phone,'add':add,'len':len(cart),'goods_list':goods_list})

@decorator.login
def user_center_order(request):
    cart = CartInfo.objects.all()
    reder = OrderInfo.objects.filter(user_id=request.session['user_id'])
    return render(request,'fresheveryday/user_center_order.html',{'len':len(cart),'reder':reder})

def user_center_site(request):
    name = request.session['user_name']
    data = FreshInfo.objects.get(fname=name)
    address = data.faddress
    return render(request,'fresheveryday/user_center_site.html',{'address':address})

# 获取post表单内容,并提交到数据库
def pic_handle(request):
    re = request.POST
    fname = re.get('user_name')
    fpwd = re.get('pwd')
    femail = re.get('email')
    re = FreshInfo.objects.filter(fname = fname).count()
    if re ==1:
        return render(request, 'fresheveryday/register.html')
    else:
        s1 = sha1()
        s1.update(fpwd)
        fpwd = s1.hexdigest()
        data = FreshInfo.objects.create(fname=fname, fpwd=fpwd, femail=femail)
        data.save()
        return render(request, 'fresheveryday/login.html', {'name': fname})


def pic_handle1(request):
    re = request.POST
    name = re.get('username')
    pwd = re.get('pwd')
    s1 = sha1()
    s1.update(pwd)
    pwd = s1.hexdigest()
    jizhu = re.get('jizhu', 0)
    dict = FreshInfo.objects.filter(fname=name)
    if len(dict) == 1:
        if dict[0].fpwd == pwd:
            url = request.COOKIES.get('url','/')
            red = redirect(url)
            red.set_cookie('url','',max_age=-1)
            if jizhu !=0:
                red.set_cookie('name', name)
            else:
                red.set_cookie('uname', '', max_age=-1)

            request.session['user_id'] = dict[0].id
            request.session['user_name'] = name
            return red
        else:
            return render(request, 'fresheveryday/login.html',{'hint':1})
    else:
        return render(request,'fresheveryday/login.html',{'hint':0})

def pic_handle2(request):
    re = request.POST
    name = request.session['user_name']
    data = FreshInfo.objects.get(fname=name)
    data.frecipients =re.get('newname')
    data.faddress =re.get('app','')
    data.fyoubian =re.get('youbian')
    data.fphone =re.get('phone')
    data.save()
    address = data.faddress
    return render(request,'fresheveryday/user_center_site.html',{'address':address,'name':name})

def loginout(request):
    request.session.flush()
    return redirect('/')

def register1(request):
    uname = request.GET.get('uname')
    count = FreshInfo.objects.filter(fname = uname).count()
    return JsonResponse({'count':count})

def user_center_orders(request,id):
    rder = OrderInfo.objects.get(pk=id)
    rder.oIsPay = True
    rder.save()
    a='9988'
    return redirect('/urls/user_center_order/',{'a':a})

fresh/templates/fresheveryday/cart.html
{%extends 'base.html'%}
{% block head %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
    function sealing (){
                len = $('.cart_list_td').length;
        $('.total_count > em').text(len);
        $('.col03 >b').text(len);
        costs = 0;
        $('.cart_list_td').each(function () {
            count = $(this).find('.num_show').val();
            price = parseFloat($(this).find('.col05').text());
            cost = count*price;
            if($(this).children('.col01').children('input').prop('checked')){
            costs +=cost;
            };
            $(this).children('.col07').children('em').text((cost).toFixed(2));
    });
            $('.settlements .col03 em').text((costs).toFixed(2));

    }

    $(function () {
            sealing();
            $('.add').click(function () {
                count = parseInt($(this).next().val());
                count +=1;
                $(this).next().val(count).blur();
                });
            $('.minus').click(function () {
                count = parseInt($(this).prev().val());
                count -=1;
                $(this).prev().val(count).blur();
            });

            $('.num_show').blur(function () {
        count=parseInt($(this).val());
        //判断库存
        kucun=parseInt($(this).parents('.col06').prevAll('.col03').children('em').text());
        if(count>=kucun){
            count=kucun;
        }
        //判断不能小于1
        if(count<=1){
            count=1;
        }
        //提交数量修改
        id=$(this).parents('.col06').prevAll('input').val();
        input_count=$(this);
        $.get('/cart/count_change/',{'id':id,'count':count},function (data) {
            input_count.val(data.count);
            sealing();
        });
    });
            });

        function del(item_id) {
        if (confirm('确定要删除吗？')){
            $.get('/cart/delete/',{'id':item_id},function (data) {
               if(data.result == 'ok'){
                   $('#'+item_id).remove();
                   sealing();
               };
            });
        };
    };

    $(function () {
        sealing();
       $('#check_all').change(function () {
            $(':checkbox:not(#check_all)').prop('checked',$(this).prop('checked'));
       }) ;
       sealing();

       $(':checkbox:not(#check_all)').change(function () {
           sealing();
           //如果$(':checkbox:not(#check_all)')的个数等于选中的chechbox(排除checkall)个数
           if ($(':checkbox:not(#check_all)').length == $(':checked:not(#check_all)').length) {
               $('#check_all').prop('checked', true);
           } else {
               $('#check_all').prop('checked', false);
           }
       });

    });


    </script>
{% endblock %}
{% block body %}

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="get" action="/cart/place_order/">
    {% for item in list %}
	<ul class="cart_list_td clearfix" id="{{ item.id }}">
        <input type="hidden" value="{{ item.id }}">
		<li class="col01"><input type="checkbox" name = 'gid' value="{{ item.id }}" checked="checked"></li>
		<li class="col02"><img src="/static/{{ item.goods.gpic }}"></li>
		<li class="col03">{{ item.goods.gtitle }}<br>库存<em>{{ item.goods.gkucun }}</em></li>
		<li class="col04">{{ item.goods.gunit }}</li>
		<li class="col05">{{ item.goods.gprice }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ item.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07"><em></em>元</li>
		<li class="col08"><a href="javascript:del({{ item.id }});">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" id="check_all" checked="checked"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>0</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>

	</ul>
    </form>
{% endblock body %}

fresh/templates/fresheveryday/detail.html
{%extends 'base.html'%}
{% block head %}
    	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
        function calcTotal() {
            coun = parseFloat($('.show_pirze > em').text());
            num = parseInt($('.num_show').val());
            $('.total > em').text((coun*num).toFixed(2));
        };

        $(function () {
            $('.num_show').blur(function () {
                calcTotal();
            });
            $('.add').click(function () {
                $('.num_show').val(parseInt($('.num_show').val())+1);
                calcTotal();
            });
            $('.minus').click(function () {
{#                获取num_show的值,并把这个值加1,在使用add赋值回去#}
                count = parseInt($('.num_show').val())-1
                if (count < 1){
                    $('.num_show').val(1);
                }else{
                    $('.num_show').val(count);
                }

                    calcTotal();
            });
        });

{#		function calcTotal() {#}
{#            price = parseFloat($('.show_pirze > em').text());#}
{#            count = parseInt($('.num_show').val());#}
{#            $('.total > em').text((price*count).toFixed(2));#}
{#        };#}
{##}
{#		$(function () {#}
{#            $('.add_cart').click(function () {#}
{#                var num = $('.total > em')#}
{#                $.get('/urls/user_center_order1/?num='+$('.show_pirze > em')+'&title='+$('.h3'),function (data) {#}
{##}
{#                });#}
{#            });#}
{#        });#}
{##}

	</script>
{% endblock head %}
{% block body %}


	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ minute.gpic }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ minute.gtitle }}</h3>
			<p>{{ minute.gjianjie }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ minute.gprice }}</em></span>
				<span class="show_unit">单  位：{{ minute.gunit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ minute.gprice }}</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for i in newest %}
                    <li>
						<a href="#"><img src="/static/{{ i.gpic }}"></a>
						<h4><a href="#">{{ i.gtitle }}</a></h4>
						<div class="prize">￥{{ i.gprice }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>名称:{{ minute.gtitle }}&nbsp;<b>介绍:</b>{{ minute.gjianjie }}</dd>
				</dl>
			</div>

		</div>
	</div>
<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript">
{#		var $add_x = $('#add_cart').offset().top;#}
{#		var $add_y = $('#add_cart').offset().left;#}
{##}
{#		var $to_x = $('#show_count').offset().top;#}
{#		var $to_y = $('#show_count').offset().left;#}
{##}
{#		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})#}
{#		$('#add_cart').click(function(){#}
{#			$(".add_jump").stop().animate({#}
{#				'left': $to_y+7,#}
{#				'top': $to_x+7},#}
{#				"fast", function() {#}
{#					$(".add_jump").fadeOut('fast',function(){#}
						//当动画播放完时，进行添加操作
                    $(function () {
                        $('.add_cart').click(function () {
                            $.get('/cart/add{{ minute.id }}_' + $('.num_show').val() + '/', function (data) {
                                $('#show_count').html(data.count);
                            });
                        });
                    });
{#					});#}
{##}
{#			});#}
{#		})#}
	</script>
{% endblock body %}

fresh/templates/fresheveryday/index.html
{%extends 'base.html'%}
{% block body %}

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

{% for item in list %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ item.types.id }}">{{ item.types.ttitle }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for i in item.fruit %}
				<a href="/detail/?a={{ i.id }}">{{ i.gtitle }}</a>
				{% endfor %}
			</div>
			<a href="/list{{ item.types.id }}_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner0{{ item.types.id }}.jpg"></div>
			<ul class="goods_list fl">
                {% for i in item.fruits %}
				<li>
					<h4><a href="/detail/">{{ i.gtitle }}</a></h4>
					<a href="/detail/?a={{ i.id }}"><img src="/static/{{ i.gpic }}"></a>
					<div class="prize">¥ {{ i.gprice }}</div>
				</li>
                {% endfor %}

			</ul>
		</div>
	</div>
{% endfor %}


{% endblock body %}
	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

fresh/templates/fresheveryday/list.html
{%extends 'base.html'%}
{% block body %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for i in list_type1 %}
					<li>
						<a href="/detail/?a={{ i.id }}"><img src="/static/{{ i.gpic }}"></a>
						<h4><a href="#">{{ i.gtitle }}</a></h4>
						<div class="prize">￥{{ i.gpirce }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="/list1_1/"class="active">默认</a>
				<a href="/list{{ id }}_1/?a=0">价格</a>
				<a href="/list{{ id }}_1/?a=1">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for i in list2 %}
				<li>
					<a href="/detail/?a={{ i.id }}"><img src="/static/{{ i.gpic }}"></a>
					<h4><a href="detail.html">{{ i.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.gpirce }}</span>
						<span class="unit">{{ i.gprice }}/{{ i.gunit }}</span>
						<a href="/cart/add{{ i.id }}_1/" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
            {% if list2.has_previous %}
				<a href="/list{{ id }}_{{ list2.number|add:-1 }}/">上一页</a>
            {% endif %}
                {% if list2.number == 1 %}
                    <a href="#" class="active">1</a>
                    <a href="/list{{ id }}_{{ list2.number|add:1 }}/">2</a>
                    <a href="/list{{ id }}_{{ list2.number|add:2 }}/">3</a>
                    <a href="/list{{ id }}_{{ list2.number|add:3 }}/">4</a>
                    <a href="/list{{ id }}_{{ list2.number|add:4 }}/">5</a>


                {% elif list2.number == 2 %}
                    <a href="/list{{ id }}_{{ list2.number|add:-1 }}/">1</a>
                    <a href="#" class="active">2</a>
                    <a href="/list{{ id }}_{{ list2.number|add:1 }}/">3</a>
                    <a href="/list{{ id }}_{{ list2.number|add:2 }}/">4</a>
                    <a href="/list{{ id }}_{{ list2.number|add:3 }}/">5</a>


                {% elif list2.number == list2.paginator.num_pages|add:-1 %}
                    <a href="/list{{ id }}_{{ list2.number|add:-3 }}/">{{ list2.number|add:-3 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:-2 }}/">{{ list2.number|add:-2 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:-1 }}/">{{ list2.number|add:-1 }}</a>
                    <a href="#" class="active">{{ list2.number }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:1 }}/">{{ list2.paginator.num_pages}}</a>

                {% elif list2.number == list2.paginator.num_pages%}
                    <a href="/list{{ id }}_{{ list2.number|add:-3 }}/">{{ list2.number|add:-4}}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:-2 }}/">{{ list2.number|add:-3 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:-1 }}/">{{ list2.number|add:-2 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:2 }}/">{{ list2.number|add:-1}}</a>
                    <a href="#" class="active">{{ list2.number }}</a>
                {% else %}
                    <a href="/list{{ id }}_{{ list2.number|add:-2 }}/">{{ list2.number|add:-2 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:-1 }}/">{{ list2.number|add:-1 }}</a>
                    <a href="#" class="active">{{ list2.number }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:1 }}/">{{ list2.number|add:1 }}</a>
                    <a href="/list{{ id }}_{{ list2.number|add:2 }}/">{{ list2.number|add:2 }}</a>
                {% endif %}

            {% if list2.has_next %}
				<a href="/list{{ id }}_{{ list2.number|add:1 }}/">下一页></a>
            {% endif %}
			</div>
		</div>
	</div>
{% endblock body %}

fresh/templates/fresheveryday/user_center_info.html
{%extends 'base.html'%}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/urls/user_center_info/" class="active">· 个人信息</a></li>
				<li><a href="/urls/user_center_order/">· 全部订单</a></li>
				<li><a href="/urls/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ name }}</li>
							<li><span>联系方式：</span>{{ phone }}</li>
							<li><span>联系地址：</span>{{ add }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                 {% for item in goods_list %}
				<li>
					<a href="/detail?a={{ item.id }}/"><img src="/static/{{ item.gpic }}"></a>
					<h4><a href='/detail?a={{ item.id }}/'>{{ item.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ item.gprice }}</span>
						<span class="unit">{{ item.gprice }}/{{ item.gunit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                 {% endfor %}
			</ul>
		</div>
		</div>
	</div>

{%endblock body%}


fresh/templates/fresheveryday/user_center_order.html
{%extends 'base.html'%}
{% block head %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
    $(function () {
        $('.order_goods_list').each(function () {
           price = parseFloat($(this).find('.col02 em').text());
           count =  parseInt($(this).find('.col03').text());
           $(this).find('.col04').text((price*count).toFixed(2));
        });
    });
    </script>
{% endblock head %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/urls/user_center_info/">· 个人信息</a></li>
				<li><a href="/urls/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/urls/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for item in reder %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ item.odate|date:"Y-m-j H:i:s" }}</li>
					<li class="col02">订单号：{{ item.oid }}</li>
                    {% if item.oIsPay%}
					<li class="col02 stress">已支付</li>
                    {% else %}
                        <li class="col02 stress">未支付</li>
                    {% endif %}
				</ul>
				<table class="order_list_table w980">

					<tbody>
						<tr>
							<td width="55%">
                                {% for i in item.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ i.goods.gpic }}"></li>
									<li class="col02">{{ i.goods.gtitle|slice:'10' }}<em>{{ i.price }}/500g</em></li>
									<li class="col03">{{ i.count }}</li>
									<li class="col04"></li>

								</ul>
                                 {% endfor %}
							</td>
							<td width="15%">{{ item.ototal }}元</td>
                            {% if item.oIsPay%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {% else %}
                            <td width="15%">待付款</td>
							<td width="15%"><a href="/urls/user_center_orders{{ item.oid }}/" class="oper_btn">去付款</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>

                {% endfor %}
				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>

{%endblock body%}